services:

  broker:
    image: confluentinc/cp-server:7.6.0
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      CLUSTER_ID: 'eMR-IFA7RgSQb3UDnGHyUw'

      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'

      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_METADATA_LOG_DIR: '/var/lib/kafka/data'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_CONFLUENT_METRICS_TOPIC_REPLICATION_FACTOR: 1  # Add this
      KAFKA_CONFLUENT_TELEMETRY_TOPIC_REPLICATION_FACTOR: 1  # Add this

      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_CLUSTER_LINK_METADATA_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081

      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      KAFKA_CONFLUENT_BALANCER_ENABLE: "false"
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

      KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600

    networks:
      - market_platform_network
    healthcheck:
      test: [ "CMD", "bash", "-c", 'nc -z localhost 9092' ]
      interval: 10s
      timeout: 5s
      retries: 5

  schema-registry:
    image: confluentinc/cp-schema-registry:8.2.2
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: WARN
      SCHEMA_REGISTRY_LOG4J_LOGGERS: >-
          org.apache.kafka=WARN,
          io.confluent=INFO,
          org.apache.kafka.clients.NetworkClient=ERROR,
          org.apache.kafka.clients.FetchSessionHandler=ERROR,
          org.apache.kafka.clients.consumer=ERROR,
          kafka=ERROR
    networks:
      - market_platform_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.6.12
    hostname: control-center
    container_name: control-center
    depends_on:
      broker:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      PORT: 9021
    networks:
      - market_platform_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9021/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow:
    container_name: airflow
    build:
      context: .
      dockerfile: airflow/Dockerfile
    command: standalone
    depends_on:
      postgres:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'false'
      AIRFLOW__LOGGING__LOGGING_LEVEL: INFO

      AIRFLOW__LOGGING__REMOTE_LOGGING: 'false'
      AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: ''
      AIRFLOW__LOGGING__HOSTNAME_CALLABLE: 'airflow.utils.log.log_reader.get_hostname'

      AIRFLOW__WEBSERVER__SECRET_KEY: 'developer-secret-key'
      AIRFLOW__API__SECRET_KEY: 'developer-secret-key'

      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_USER_CREATE: 'true'

      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: 'admin1'
      _AIRFLOW_WWW_USER_PASSWORD: 'admin1'
      _AIRFLOW_WWW_USER_FIRSTNAME: 'Admin'
      _AIRFLOW_WWW_USER_LASTNAME: 'User'
      _AIRFLOW_WWW_USER_EMAIL: 'admin@example.com'
      _AIRFLOW_WWW_USER_ROLE: 'Admin'

    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    networks:
      - market_platform_network

  postgres:
    container_name: postgres_db
    image: postgres:16.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - market_platform_network

#  spark-master:
#    image: bitnami/spark:latest
#    command: bin/spark-class org.apache.spark.deploy.master.Master
#    ports:
#      - "9090:8080"
#      - "7077:7077"
#    networks:
#      - market_platform_network
#
#  spark-worker:
#    image: bitnami/spark:latest
#    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
#    depends_on:
#      - spark-master
#    environment:
#      SPARK_MODE: worker
#      SPARK_WORKER_CORES: 2
#      SPARK_WORKER_MEMORY: 1g
#      SPARK_MASTER_URL: spark://spark-master:7077
#    networks:
#      - market_platform_network

networks:
  market_platform_network: