[project]
name = "market-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiokafka>=0.14.0",
    "apache-airflow>=3.2.2",
    "apache-airflow-providers-fab>=3.7.1",
    "kafka>=1.3.5",
    "kafka-python-ng>=2.2.3",
    "psycopg2-binary>=2.9.12",
    "werkzeug>=3.1.8",
    "yfinance>=1.4.1",
]
